language: java
jdk:
  - oraclejdk8
# do not install anything instead return true via unix command true
install: true
script: mvn clean test
notifications:
  email:
    - github@graphhopper.com

# enable container-based stack
sudo: false

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true
