# general settings:
# http://www.dropwizard.io/manual/configuration.html

server:
  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO

  loggers:
    "org.hibernate": INFO

  appenders:
    - type: console
      timeZone: UTC
      logFormat: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"



